name: Imported Mesh Emergency Room
description: This is an image: ![alt text](./images/fbx-export.png)
title: "[Imported Mesh]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to reach out to us about your imported mesh. This form is intended to organize models and educate our users on best practices and troublshooting methods for imported meshes. In order to establish some common ground, we ask that you please download the free and open source software Blender, you can do so by using this [Link](https://www.blender.org/). Once you have installed Blender, please take the time to import your mesh into a scene to confirm that a 3rd party software can appropriately read the mesh and animation data. If the mesh works in Blender, but doesn't work in EmberGen, try exporting that same file from Blender into EmberGen. If it does work, we ask that you do not fill this form out, as we want to limit the amount of time we spend fixing errors caused by irregularites from other 3D engines. Blender is a much more stable frame of reference for us to work from, and will allow us to more quickly address the problem if it remains.

  - type: textarea
    id: email
    attributes:
      label: Email
      description: Please provide your email so that we can contact you personally about this file
      placeholder: your@email.com
    validations:
      required: true
  
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a detailed description of the expected behavior of your mesh and the behavior observed in EmberGen
      placeholder: Step 1. Open EmberGen. Step 2. Turn on Smooth UI....
    validations:
      required: true
      
  - type: textarea
    id: file
    attributes:
      label: File Upload
      description: Please upload a zip file or link to a zip file that includes the animated mesh, embergen preset, and project file (backplates are not necessary).
      placeholder: example.zip
    validations:
      required: true
      
  - type: dropdown
    id: file-type
    attributes:
      label: File Type
      description: What kind of file are you using?
      options:
        - fbx
        - abc
        - obj
    validations:
      required: true
      
  - type: dropdown
    id: origin
    attributes:
      label: Origin Software
      description: What software was used to create this file?
      options:
        - Blender
        - Maya
        - Cinema4D
        - Houdini
        - 3DS Max
        - other / unknown
    validations:
      required: true
           
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Submission Agreement
      description: By submitting this issue, you agree to the following statement
      options:
        - label: I do solemnly swear that I tested this issue in Dev.
          required: true
