name: Imported Mesh Emergency Room
description: Imported Mesh File
title: "[Imported Mesh]: "
labels: bug
body:


        
  - type: textarea
    id: email
    attributes:
      label: Email
      description: Please provide your email so that we can contact you personally about this file
      placeholder: your@email.com
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a detailed description of the expected behavior of your mesh and the behavior observed in EmberGen
      placeholder: Step 1. Open EmberGen. Step 2. Turn on Smooth UI....
    validations:
      required: true
      
  - type: textarea
    id: file
    attributes:
      label: File Upload
      description: Please upload a zip file or link to a zip file that includes the animated mesh, embergen preset, and project file (backplates are not necessary).
      placeholder: example.zip
    validations:
      required: true
      
   - type: dropdown
    id: file type
    attributes:
      label: File Type
      description: What kind of file are you using?
      options:
        - fbx
        - abc
        - obj
    validations:
      required: true
      
  - type: dropdown
    id: origin
    attributes:
      label: Origin Software
      description: What software was used to create this file?
      options:
        - Blender
        - Maya
        - Cinema4D
        - Houdini
        - 3DS Max
        - other / unknown
    validations:
      required: true
           
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Submission Agreement
      description: By submitting this issue, you agree to the following statement
      options:
        - label: I do solemnly swear that I tested this issue in Dev.
          required: true
